version: "3"

services:
  live_transmit:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/sls:${BUILD_VERSION}
    ports:
      - target: 1935
        published: 1935
        protocol: udp
        mode: host
    deploy:
      mode: global
      restart_policy:
        condition: on-failure