version: "3"

services:
  live_transmit_1:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/sls:${BUILD_VERSION}
    ports:
      - target: 1935
        published: 1935
        protocol: udp
        mode: host
    environment:
      - LISTEN_PORT=1935
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - live_transmit1_logs:/home/sls/logs

  live_transmit_2:
    image: ${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_ID}/sls:${BUILD_VERSION}
    ports:
      - target: 1936
        published: 1936
        protocol: udp
        mode: host
    environment:
      - LISTEN_PORT=1936
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - live_transmit2_logs:/home/sls/logs

volumes:
  live_transmit1_logs:
  live_transmit2_logs: