name: SLS pipeline

on:
  push:
    tags: [ "*" ]
    branches: [ "*" ]
    paths-ignore:
      - "iac/*.tf"
      - "iac/*.sh"
      - "deploy.sh"
      - "undeploy.sh"
      - "*.md"
      - "LICENSE"

permissions:
  contents: read

jobs:
  build:
    name: Jobs
    runs-on: ubuntu-latest

    steps:
      - name: Download the project files.
        uses: actions/checkout@v3

      - name: Build services.
        run: ./build.sh

      - name: Publish services.
        env:
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        run: ./publish.sh
